//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeWebApplication.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        private int employeeIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int employeeID {
            get {
                return this.employeeIDField;
            }
            set {
                if ((this.employeeIDField.Equals(value) != true)) {
                    this.employeeIDField = value;
                    this.RaisePropertyChanged("employeeID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Generating message contract since the wrapper name (For_x0020_adding_x0020_an_x0020_employee_x0020_and_x0020_getting_x0020_the_x0020_whole_x0020_employee_x0020_list) of message For_x0020_adding_x0020_an_x0020_employee_x0020_and_x0020_getting_x0020_the_x0020_whole_x0020_employee_x0020_list does not match the default value (AddEmployee)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/For adding an employee and getting the whole employee list", ReplyAction="*")]
        EmployeeWebApplication.ServiceReference1.Foraddinganemployeeandgettingthewholeemployeelist1 AddEmployee(EmployeeWebApplication.ServiceReference1.Foraddinganemployeeandgettingthewholeemployeelist request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/For adding an employee and getting the whole employee list", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeWebApplication.ServiceReference1.Foraddinganemployeeandgettingthewholeemployeelist1> AddEmployeeAsync(EmployeeWebApplication.ServiceReference1.Foraddinganemployeeandgettingthewholeemployeelist request);
        
        // CODEGEN: Generating message contract since the wrapper name (For_x0020_removing_x0020_an_x0020_employee_x0020_and_x0020_getting_x0020_the_x0020_whole_x0020_employee_x0020_list) of message For_x0020_removing_x0020_an_x0020_employee_x0020_and_x0020_getting_x0020_the_x0020_whole_x0020_employee_x0020_list does not match the default value (RemoveEmployee)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/For removing an employee and getting the whole employee list", ReplyAction="*")]
        EmployeeWebApplication.ServiceReference1.Forremovinganemployeeandgettingthewholeemployeelist1 RemoveEmployee(EmployeeWebApplication.ServiceReference1.Forremovinganemployeeandgettingthewholeemployeelist request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/For removing an employee and getting the whole employee list", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeWebApplication.ServiceReference1.Forremovinganemployeeandgettingthewholeemployeelist1> RemoveEmployeeAsync(EmployeeWebApplication.ServiceReference1.Forremovinganemployeeandgettingthewholeemployeelist request);
        
        // CODEGEN: Generating message contract since the wrapper name (For_x0020_updating_x0020_the_x0020_first_x0020_name_x0020_of_x0020_an_x0020_employee_x0020_and_x0020_getting_x0020_the_x0020_whole_x0020_employee_x0020_list) of message For_x0020_updating_x0020_the_x0020_first_x0020_name_x0020_of_x0020_an_x0020_employee_x0020_and_x0020_getting_x0020_the_x0020_whole_x0020_employee_x0020_list does not match the default value (UpdateEmployeeFirstName)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/For updating the first name of an employee and getting the who" +
            "le employee list", ReplyAction="*")]
        EmployeeWebApplication.ServiceReference1.Forupdatingthefirstnameofanemployeeandgettingthewholeemployeelist1 UpdateEmployeeFirstName(EmployeeWebApplication.ServiceReference1.Forupdatingthefirstnameofanemployeeandgettingthewholeemployeelist request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/For updating the first name of an employee and getting the who" +
            "le employee list", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeWebApplication.ServiceReference1.Forupdatingthefirstnameofanemployeeandgettingthewholeemployeelist1> UpdateEmployeeFirstNameAsync(EmployeeWebApplication.ServiceReference1.Forupdatingthefirstnameofanemployeeandgettingthewholeemployeelist request);
        
        // CODEGEN: Generating message contract since the wrapper name (For_x0020_updating_x0020_the_x0020_last_x0020_name_x0020_of_x0020_an_x0020_employee_x0020_and_x0020_getting_x0020_the_x0020_whole_x0020_employee_x0020_list) of message For_x0020_updating_x0020_the_x0020_last_x0020_name_x0020_of_x0020_an_x0020_employee_x0020_and_x0020_getting_x0020_the_x0020_whole_x0020_employee_x0020_list does not match the default value (UpdateEmployeeLastName)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/For updating the last name of an employee and getting the whol" +
            "e employee list", ReplyAction="*")]
        EmployeeWebApplication.ServiceReference1.Forupdatingthelastnameofanemployeeandgettingthewholeemployeelist1 UpdateEmployeeLastName(EmployeeWebApplication.ServiceReference1.Forupdatingthelastnameofanemployeeandgettingthewholeemployeelist request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/For updating the last name of an employee and getting the whol" +
            "e employee list", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeWebApplication.ServiceReference1.Forupdatingthelastnameofanemployeeandgettingthewholeemployeelist1> UpdateEmployeeLastNameAsync(EmployeeWebApplication.ServiceReference1.Forupdatingthelastnameofanemployeeandgettingthewholeemployeelist request);
        
        // CODEGEN: Generating message contract since the wrapper name (For_x0020_getting_x0020_tha_x0020_name_x0020_of_x0020_the_x0020_employee) of message For_x0020_getting_x0020_tha_x0020_name_x0020_of_x0020_the_x0020_employee does not match the default value (GetEmployee)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/For getting tha name of the employee", ReplyAction="*")]
        EmployeeWebApplication.ServiceReference1.Forgettingthanameoftheemployee1 GetEmployee(EmployeeWebApplication.ServiceReference1.Forgettingthanameoftheemployee request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/For getting tha name of the employee", ReplyAction="*")]
        System.Threading.Tasks.Task<EmployeeWebApplication.ServiceReference1.Forgettingthanameoftheemployee1> GetEmployeeAsync(EmployeeWebApplication.ServiceReference1.Forgettingthanameoftheemployee request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="For adding an employee and getting the whole employee list", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Foraddinganemployeeandgettingthewholeemployeelist {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string firstName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string lastName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int employeeID;
        
        public Foraddinganemployeeandgettingthewholeemployeelist() {
        }
        
        public Foraddinganemployeeandgettingthewholeemployeelist(string firstName, string lastName, int employeeID) {
            this.firstName = firstName;
            this.lastName = lastName;
            this.employeeID = employeeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="For adding an employee and getting the whole employee listResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Foraddinganemployeeandgettingthewholeemployeelist1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="For_x0020_adding_x0020_an_x0020_employee_x0020_and_x0020_getting_x0020_the_x0020_" +
            "whole_x0020_employee_x0020_listResult", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeWebApplication.ServiceReference1.Employee[] ForaddinganemployeeandgettingthewholeemployeelistResult;
        
        public Foraddinganemployeeandgettingthewholeemployeelist1() {
        }
        
        public Foraddinganemployeeandgettingthewholeemployeelist1(EmployeeWebApplication.ServiceReference1.Employee[] ForaddinganemployeeandgettingthewholeemployeelistResult) {
            this.ForaddinganemployeeandgettingthewholeemployeelistResult = ForaddinganemployeeandgettingthewholeemployeelistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="For removing an employee and getting the whole employee list", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Forremovinganemployeeandgettingthewholeemployeelist {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public Forremovinganemployeeandgettingthewholeemployeelist() {
        }
        
        public Forremovinganemployeeandgettingthewholeemployeelist(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="For removing an employee and getting the whole employee listResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Forremovinganemployeeandgettingthewholeemployeelist1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="For_x0020_removing_x0020_an_x0020_employee_x0020_and_x0020_getting_x0020_the_x002" +
            "0_whole_x0020_employee_x0020_listResult", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeWebApplication.ServiceReference1.Employee[] ForremovinganemployeeandgettingthewholeemployeelistResult;
        
        public Forremovinganemployeeandgettingthewholeemployeelist1() {
        }
        
        public Forremovinganemployeeandgettingthewholeemployeelist1(EmployeeWebApplication.ServiceReference1.Employee[] ForremovinganemployeeandgettingthewholeemployeelistResult) {
            this.ForremovinganemployeeandgettingthewholeemployeelistResult = ForremovinganemployeeandgettingthewholeemployeelistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="For updating the first name of an employee and getting the whole employee list", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Forupdatingthefirstnameofanemployeeandgettingthewholeemployeelist {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string firstName;
        
        public Forupdatingthefirstnameofanemployeeandgettingthewholeemployeelist() {
        }
        
        public Forupdatingthefirstnameofanemployeeandgettingthewholeemployeelist(int id, string firstName) {
            this.id = id;
            this.firstName = firstName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="For updating the first name of an employee and getting the whole employee listRes" +
        "ponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Forupdatingthefirstnameofanemployeeandgettingthewholeemployeelist1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="For_x0020_updating_x0020_the_x0020_first_x0020_name_x0020_of_x0020_an_x0020_emplo" +
            "yee_x0020_and_x0020_getting_x0020_the_x0020_whole_x0020_employee_x0020_listResul" +
            "t", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeWebApplication.ServiceReference1.Employee[] ForupdatingthefirstnameofanemployeeandgettingthewholeemployeelistResult;
        
        public Forupdatingthefirstnameofanemployeeandgettingthewholeemployeelist1() {
        }
        
        public Forupdatingthefirstnameofanemployeeandgettingthewholeemployeelist1(EmployeeWebApplication.ServiceReference1.Employee[] ForupdatingthefirstnameofanemployeeandgettingthewholeemployeelistResult) {
            this.ForupdatingthefirstnameofanemployeeandgettingthewholeemployeelistResult = ForupdatingthefirstnameofanemployeeandgettingthewholeemployeelistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="For updating the last name of an employee and getting the whole employee list", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Forupdatingthelastnameofanemployeeandgettingthewholeemployeelist {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string lastName;
        
        public Forupdatingthelastnameofanemployeeandgettingthewholeemployeelist() {
        }
        
        public Forupdatingthelastnameofanemployeeandgettingthewholeemployeelist(int id, string lastName) {
            this.id = id;
            this.lastName = lastName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="For updating the last name of an employee and getting the whole employee listResp" +
        "onse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Forupdatingthelastnameofanemployeeandgettingthewholeemployeelist1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="For_x0020_updating_x0020_the_x0020_last_x0020_name_x0020_of_x0020_an_x0020_employ" +
            "ee_x0020_and_x0020_getting_x0020_the_x0020_whole_x0020_employee_x0020_listResult" +
            "", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeWebApplication.ServiceReference1.Employee[] ForupdatingthelastnameofanemployeeandgettingthewholeemployeelistResult;
        
        public Forupdatingthelastnameofanemployeeandgettingthewholeemployeelist1() {
        }
        
        public Forupdatingthelastnameofanemployeeandgettingthewholeemployeelist1(EmployeeWebApplication.ServiceReference1.Employee[] ForupdatingthelastnameofanemployeeandgettingthewholeemployeelistResult) {
            this.ForupdatingthelastnameofanemployeeandgettingthewholeemployeelistResult = ForupdatingthelastnameofanemployeeandgettingthewholeemployeelistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="For getting tha name of the employee", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Forgettingthanameoftheemployee {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public Forgettingthanameoftheemployee() {
        }
        
        public Forgettingthanameoftheemployee(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="For getting tha name of the employeeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Forgettingthanameoftheemployee1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="For_x0020_getting_x0020_tha_x0020_name_x0020_of_x0020_the_x0020_employeeResult", Namespace="http://tempuri.org/", Order=0)]
        public EmployeeWebApplication.ServiceReference1.Employee ForgettingthanameoftheemployeeResult;
        
        public Forgettingthanameoftheemployee1() {
        }
        
        public Forgettingthanameoftheemployee1(EmployeeWebApplication.ServiceReference1.Employee ForgettingthanameoftheemployeeResult) {
            this.ForgettingthanameoftheemployeeResult = ForgettingthanameoftheemployeeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : EmployeeWebApplication.ServiceReference1.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<EmployeeWebApplication.ServiceReference1.WebService1Soap>, EmployeeWebApplication.ServiceReference1.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeWebApplication.ServiceReference1.Foraddinganemployeeandgettingthewholeemployeelist1 EmployeeWebApplication.ServiceReference1.WebService1Soap.AddEmployee(EmployeeWebApplication.ServiceReference1.Foraddinganemployeeandgettingthewholeemployeelist request) {
            return base.Channel.AddEmployee(request);
        }
        
        public EmployeeWebApplication.ServiceReference1.Employee[] AddEmployee(string firstName, string lastName, int employeeID) {
            EmployeeWebApplication.ServiceReference1.Foraddinganemployeeandgettingthewholeemployeelist inValue = new EmployeeWebApplication.ServiceReference1.Foraddinganemployeeandgettingthewholeemployeelist();
            inValue.firstName = firstName;
            inValue.lastName = lastName;
            inValue.employeeID = employeeID;
            EmployeeWebApplication.ServiceReference1.Foraddinganemployeeandgettingthewholeemployeelist1 retVal = ((EmployeeWebApplication.ServiceReference1.WebService1Soap)(this)).AddEmployee(inValue);
            return retVal.ForaddinganemployeeandgettingthewholeemployeelistResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeWebApplication.ServiceReference1.Foraddinganemployeeandgettingthewholeemployeelist1> EmployeeWebApplication.ServiceReference1.WebService1Soap.AddEmployeeAsync(EmployeeWebApplication.ServiceReference1.Foraddinganemployeeandgettingthewholeemployeelist request) {
            return base.Channel.AddEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeWebApplication.ServiceReference1.Foraddinganemployeeandgettingthewholeemployeelist1> AddEmployeeAsync(string firstName, string lastName, int employeeID) {
            EmployeeWebApplication.ServiceReference1.Foraddinganemployeeandgettingthewholeemployeelist inValue = new EmployeeWebApplication.ServiceReference1.Foraddinganemployeeandgettingthewholeemployeelist();
            inValue.firstName = firstName;
            inValue.lastName = lastName;
            inValue.employeeID = employeeID;
            return ((EmployeeWebApplication.ServiceReference1.WebService1Soap)(this)).AddEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeWebApplication.ServiceReference1.Forremovinganemployeeandgettingthewholeemployeelist1 EmployeeWebApplication.ServiceReference1.WebService1Soap.RemoveEmployee(EmployeeWebApplication.ServiceReference1.Forremovinganemployeeandgettingthewholeemployeelist request) {
            return base.Channel.RemoveEmployee(request);
        }
        
        public EmployeeWebApplication.ServiceReference1.Employee[] RemoveEmployee(int id) {
            EmployeeWebApplication.ServiceReference1.Forremovinganemployeeandgettingthewholeemployeelist inValue = new EmployeeWebApplication.ServiceReference1.Forremovinganemployeeandgettingthewholeemployeelist();
            inValue.id = id;
            EmployeeWebApplication.ServiceReference1.Forremovinganemployeeandgettingthewholeemployeelist1 retVal = ((EmployeeWebApplication.ServiceReference1.WebService1Soap)(this)).RemoveEmployee(inValue);
            return retVal.ForremovinganemployeeandgettingthewholeemployeelistResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeWebApplication.ServiceReference1.Forremovinganemployeeandgettingthewholeemployeelist1> EmployeeWebApplication.ServiceReference1.WebService1Soap.RemoveEmployeeAsync(EmployeeWebApplication.ServiceReference1.Forremovinganemployeeandgettingthewholeemployeelist request) {
            return base.Channel.RemoveEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeWebApplication.ServiceReference1.Forremovinganemployeeandgettingthewholeemployeelist1> RemoveEmployeeAsync(int id) {
            EmployeeWebApplication.ServiceReference1.Forremovinganemployeeandgettingthewholeemployeelist inValue = new EmployeeWebApplication.ServiceReference1.Forremovinganemployeeandgettingthewholeemployeelist();
            inValue.id = id;
            return ((EmployeeWebApplication.ServiceReference1.WebService1Soap)(this)).RemoveEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeWebApplication.ServiceReference1.Forupdatingthefirstnameofanemployeeandgettingthewholeemployeelist1 EmployeeWebApplication.ServiceReference1.WebService1Soap.UpdateEmployeeFirstName(EmployeeWebApplication.ServiceReference1.Forupdatingthefirstnameofanemployeeandgettingthewholeemployeelist request) {
            return base.Channel.UpdateEmployeeFirstName(request);
        }
        
        public EmployeeWebApplication.ServiceReference1.Employee[] UpdateEmployeeFirstName(int id, string firstName) {
            EmployeeWebApplication.ServiceReference1.Forupdatingthefirstnameofanemployeeandgettingthewholeemployeelist inValue = new EmployeeWebApplication.ServiceReference1.Forupdatingthefirstnameofanemployeeandgettingthewholeemployeelist();
            inValue.id = id;
            inValue.firstName = firstName;
            EmployeeWebApplication.ServiceReference1.Forupdatingthefirstnameofanemployeeandgettingthewholeemployeelist1 retVal = ((EmployeeWebApplication.ServiceReference1.WebService1Soap)(this)).UpdateEmployeeFirstName(inValue);
            return retVal.ForupdatingthefirstnameofanemployeeandgettingthewholeemployeelistResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeWebApplication.ServiceReference1.Forupdatingthefirstnameofanemployeeandgettingthewholeemployeelist1> EmployeeWebApplication.ServiceReference1.WebService1Soap.UpdateEmployeeFirstNameAsync(EmployeeWebApplication.ServiceReference1.Forupdatingthefirstnameofanemployeeandgettingthewholeemployeelist request) {
            return base.Channel.UpdateEmployeeFirstNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeWebApplication.ServiceReference1.Forupdatingthefirstnameofanemployeeandgettingthewholeemployeelist1> UpdateEmployeeFirstNameAsync(int id, string firstName) {
            EmployeeWebApplication.ServiceReference1.Forupdatingthefirstnameofanemployeeandgettingthewholeemployeelist inValue = new EmployeeWebApplication.ServiceReference1.Forupdatingthefirstnameofanemployeeandgettingthewholeemployeelist();
            inValue.id = id;
            inValue.firstName = firstName;
            return ((EmployeeWebApplication.ServiceReference1.WebService1Soap)(this)).UpdateEmployeeFirstNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeWebApplication.ServiceReference1.Forupdatingthelastnameofanemployeeandgettingthewholeemployeelist1 EmployeeWebApplication.ServiceReference1.WebService1Soap.UpdateEmployeeLastName(EmployeeWebApplication.ServiceReference1.Forupdatingthelastnameofanemployeeandgettingthewholeemployeelist request) {
            return base.Channel.UpdateEmployeeLastName(request);
        }
        
        public EmployeeWebApplication.ServiceReference1.Employee[] UpdateEmployeeLastName(int id, string lastName) {
            EmployeeWebApplication.ServiceReference1.Forupdatingthelastnameofanemployeeandgettingthewholeemployeelist inValue = new EmployeeWebApplication.ServiceReference1.Forupdatingthelastnameofanemployeeandgettingthewholeemployeelist();
            inValue.id = id;
            inValue.lastName = lastName;
            EmployeeWebApplication.ServiceReference1.Forupdatingthelastnameofanemployeeandgettingthewholeemployeelist1 retVal = ((EmployeeWebApplication.ServiceReference1.WebService1Soap)(this)).UpdateEmployeeLastName(inValue);
            return retVal.ForupdatingthelastnameofanemployeeandgettingthewholeemployeelistResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeWebApplication.ServiceReference1.Forupdatingthelastnameofanemployeeandgettingthewholeemployeelist1> EmployeeWebApplication.ServiceReference1.WebService1Soap.UpdateEmployeeLastNameAsync(EmployeeWebApplication.ServiceReference1.Forupdatingthelastnameofanemployeeandgettingthewholeemployeelist request) {
            return base.Channel.UpdateEmployeeLastNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeWebApplication.ServiceReference1.Forupdatingthelastnameofanemployeeandgettingthewholeemployeelist1> UpdateEmployeeLastNameAsync(int id, string lastName) {
            EmployeeWebApplication.ServiceReference1.Forupdatingthelastnameofanemployeeandgettingthewholeemployeelist inValue = new EmployeeWebApplication.ServiceReference1.Forupdatingthelastnameofanemployeeandgettingthewholeemployeelist();
            inValue.id = id;
            inValue.lastName = lastName;
            return ((EmployeeWebApplication.ServiceReference1.WebService1Soap)(this)).UpdateEmployeeLastNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EmployeeWebApplication.ServiceReference1.Forgettingthanameoftheemployee1 EmployeeWebApplication.ServiceReference1.WebService1Soap.GetEmployee(EmployeeWebApplication.ServiceReference1.Forgettingthanameoftheemployee request) {
            return base.Channel.GetEmployee(request);
        }
        
        public EmployeeWebApplication.ServiceReference1.Employee GetEmployee(int id) {
            EmployeeWebApplication.ServiceReference1.Forgettingthanameoftheemployee inValue = new EmployeeWebApplication.ServiceReference1.Forgettingthanameoftheemployee();
            inValue.id = id;
            EmployeeWebApplication.ServiceReference1.Forgettingthanameoftheemployee1 retVal = ((EmployeeWebApplication.ServiceReference1.WebService1Soap)(this)).GetEmployee(inValue);
            return retVal.ForgettingthanameoftheemployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EmployeeWebApplication.ServiceReference1.Forgettingthanameoftheemployee1> EmployeeWebApplication.ServiceReference1.WebService1Soap.GetEmployeeAsync(EmployeeWebApplication.ServiceReference1.Forgettingthanameoftheemployee request) {
            return base.Channel.GetEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<EmployeeWebApplication.ServiceReference1.Forgettingthanameoftheemployee1> GetEmployeeAsync(int id) {
            EmployeeWebApplication.ServiceReference1.Forgettingthanameoftheemployee inValue = new EmployeeWebApplication.ServiceReference1.Forgettingthanameoftheemployee();
            inValue.id = id;
            return ((EmployeeWebApplication.ServiceReference1.WebService1Soap)(this)).GetEmployeeAsync(inValue);
        }
    }
}
